[tracks.dev]
repo = "hiroshi-manabe/yomi-corpus"
pages_url = "https://hiroshi-manabe.github.io/yomi-corpus/review/"
publish_mode = "local"

[tracks.working]
repo = "hiroshi-manabe/yomi-corpus"
pages_url = "https://hiroshi-manabe.github.io/yomi-corpus/review/"
publish_mode = "local"
