[sudachi]
command = "/home/hmanabe/scripts/sudachi"
args = ["-a"]

[decoder]
python = "python"
script = "../../../yomi-decoder/scripts/decode.py"
config = "../../../yomi-decoder/config/default.toml"
beam = 150
nbest = 5

[strategy]
default = "agreement_prefer_decoder_v1"
