strict_case_max_length = 3

[lists]
whitelist = "config/alphabetic/minor_whitelist.txt"
blacklist = "config/alphabetic/minor_blacklist.txt"
case_sensitive_whitelist = "config/alphabetic/case_sensitive_whitelist.txt"
case_sensitive_blacklist = "config/alphabetic/case_sensitive_blacklist.txt"
